# Generated by Django 4.0.5 on 2022-08-18 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_skill_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='date',
        ),
    ]
