# Generated by Django 4.0.4 on 2022-08-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_lesson_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='week',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='demo',
            name='week',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='week',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='week',
            field=models.IntegerField(null=True),
        ),
    ]
