# Generated by Django 4.0.4 on 2022-08-19 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_chapter_week_demo_week_project_week_skill_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('week', models.IntegerField(null=True)),
                ('title', models.CharField(default='No title', max_length=200)),
                ('doctype', models.CharField(max_length=200)),
                ('course', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
