# Generated by Django 4.0.5 on 2022-08-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_author_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
