# Generated by Django 4.0.4 on 2022-08-30 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='project',
            name='course',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='course',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Demo',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
