# Generated by Django 4.0.5 on 2022-10-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_course_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
