# Generated by Django 4.0.4 on 2022-10-11 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_content_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='week',
        ),
    ]
