#!/bin/bash
# Linux Shell Contexts

# Path Context
syspath="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
pyenv=/Users/seaman/.pyenv/versions/3.10.4/bin
brew=/opt/homebrew/bin:/opt/homebrew/sbin
sublime="/Applications/Sublime Text.app/Contents/SharedSupport/bin"
vscode1="/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
vscode2="/private/var/folders/ch/23b6bkbj5t90h339h0pjyvh80000gn/T/AppTranslocation/*/d/Visual Studio Code 2.app/Contents/Resources/app/bin"
export PATH="$pyenv:$brew:$sublime:$vscode1:$vscode2:$syspath"


# Variables
export p=~/Hammer
export h=~/Hammer
export d=$p/Documents
export g=$HOME/Github
export c=$d/shrinking-world.com/webapps1
export cx=$d/Github/WebApps-1
export a=$HOME/Archive
export i=$d/markseaman.info
export m="$a/rcp/mbw"
export n=$a/ntsh
export s=$d/seamanslog.com/sampler/12
export t=$i/history/2022/12
export w=$d/seamansguide.com/webapps
export course=$c
export slog=$s
export blog=$d/shrinking-world.com/blog
export book=$d/seamansguide.com
export green=$d/shrinking-world.com/greenhouse
export PS1="%3~ : "
export EDITOR="subl -w"


# Project Context
alias e='subl'
alias ea='subl ~/Hammer/config/zshrc'
alias hammer="source ~/.zshrc && code $p"
alias book='subl $book'
alias course='subl $course $cx'
alias slog='subl $slog'
alias blog='pm write blog'
alias docs='subl Documents'
alias demo='code $g/PythonWebApps'
alias masto='write masto'
alias review='write review'
alias teach='pm teach'
alias tech='pm write tech'
alias task='pm task'
alias write='pm write'
alias words='write words'
alias cprc='cp ~/Hammer/config/zshrc ~/.zshrc && . ~/.zshrc'

# Workflow
alias todo='pm todo'
alias build='d && pm build'
alias epub='d $w && open textbook.epub'
alias dropbox='cp $w/textbook.epub ~/Dropbox/Stacie-Mark/PythonWebApps'
alias m='e Documents/mastodon'

# Linux command context
alias g='grep --color=auto'
alias l='ls -al'
alias u='d ..'
alias host=hostname
alias h='history 100'
alias p=python

# Git aliases
alias s='git status'
alias gh='d $g'
alias gl='git log --name-only'
alias gd='git diff'
alias ga='git add -A . && git commit -m'
alias gco='git checkout'
alias vc='cd $p && pm vc'
alias pull='pm vc pull'
alias push='pm vc push'
alias deploy='pm vc deploy'

# Django aliases
alias pm='python manage.py'
alias r='pm runserver 8000'
alias t='pm test'
alias serve='pm runserver 8000'
alias dt='pm test'
alias migrate='pm makemigrations && pm migrate'
alias mm='pm makemigrations'
alias web='open http://markseaman.info'
alias w='open http://markseaman.info'

# Servers
alias imac='ssh seaman@marks-imac.local'
alias macbook='ssh markseaman@marks-macbook.local'
alias ntsh='. $n/zshrc'
alias unpack='pm pack open'
alias pack='pm pack close'
alias imager='pm imager'

# Test aliases
alias tst='pm tst run'
alias tlike='pm tst like && tst'
alias tres='pm tst results | less'
alias treset='pm tst reset'
alias qt='pm tst quick'



# Linux functions
function d {
    directory=$1
    [ -z "$1" ] && directory="$p"
    [ -z "$1" ] || echo $directory && cd $directory && l
}

# Big commit on current directory
function c {
    git pull           &&
    git add -A .       &&
    git commit -m "$*" &&
    git push
    git status
}

# Small commit on current directory
function gc {
    git add -A .       &&
    git commit -m "$*"
}

# Copy a file tree
function cptree {
    rsync -auv "$1/" "$2"
}

# Create a post on mastodon
function post {
    msg=`cat Documents/mastodon/$1`
    echo toot post \"$msg\"
}

# List the path in readable form
function path {
    echo $PATH | perl -pe s/:/\\n/g
}

# Show the Python setup
function py {
    echo "Python environment"
    echo PYTHON_PATH = `which python`
    echo PYENV = `pyenv which python`
    echo "Python Packages"
    pip freeze
}



# Demo Code

export b3=$HOME/Github/PythonWebApps
export s=$cx/Superhero
export p1=$cx/01
export p2=$cx/02
export p3=$cx/03
export p4=$cx/04
export p5=$cx/05
export p6=$cx/06
export p7=$cx/07
export p8=$cx/08
export p9=$cx/09
export p10=$cx/10
export p11=$cx/11
export p12=$cx/12

alias p1='cd $p1 && l'
alias p2='cd $p2 && l'
alias p3='cd $p3 && l'
alias p4='cd $p4 && l'
alias p5='cd $p5 && l'
alias p6='cd $p6 && l'
alias p7='cd $p7 && l'
alias p8='cd $p8 && l'
alias p9='cd $p9 && l'
alias p10='cd $p10 && l'
alias p11='cd $p11 && l'
alias p12='cd $p12 && l'
alias p13='cd $p13 && l'
alias p14='cd $p14 && l'

alias superuser='pm createsuperuser --no-input  --email "me@here.us"'

# DocEnv
export DJANGO_SUPERUSER_USERNAME='seaman'
export DJANGO_SUPERUSER_PASSWORD='seaman'
export DJANGO_SUPERUSER_EMAIL='seaman'


# Banner
figlet Hammer Time


# # Node environment
# export NVM_DIR="$HOME/.nvm"
# [[ -s "$NVM_DIR/nvm.sh" ]] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [[ -s "$NVM_DIR/bash_completion" ]] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# export PYENV_ROOT="$HOME/.pyenv"
# command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
# eval "$(pyenv init -)"

cd ~/Hammer
ls
