#!/bin/bash
# Linux Shell Contexts

# Path Context
syspath="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
pyenv=/Users/seaman/.pyenv/versions/3.10.4/bin
brew=/opt/homebrew/bin:/opt/homebrew/sbin
sublime="/Applications/Sublime Text.app/Contents/SharedSupport/bin"
vscode1="/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
vscode2="/private/var/folders/ch/23b6bkbj5t90h339h0pjyvh80000gn/T/AppTranslocation/*/d/Visual Studio Code 2.app/Contents/Resources/app/bin"
export PATH="$pyenv:$brew:$sublime:$vscode1:$vscode2:$syspath"


# Variables
export p=~/Hammer
export h=~/Hammer
export d=$p/Documents
export g=$HOME/Github
export c=$d/shrinking-world.com/webapps1
export cx=$d/Github/WebApps-1
export a=$HOME/Archive
export i=$d/markseaman.info
export m="$a/rcp/mbw"
export n=$a/ntsh
export s=$d/seamanslog.com/sampler
export t=$i/history/2023/01
export w=$d/seamansguide.com/webapps
export course=$c
export slog=$s
export blog=$d/shrinking-world.com/blog
export book=$d/seamansguide.com
export green=$d/shrinking-world.com/greenhouse
export EDITOR="subl -w"


# Project Scripts
alias book='subl $book'
alias course='subl $course $cx'
alias blog='pm write blog'
alias demo='code $g/PythonWebApps'
alias docs='subl Documents'
alias e='subl'
alias ea='subl ~/Hammer/config/zshrc'
alias green='write green'
alias hammer="source ~/.zshrc && code $p"
alias masto='write masto'
alias review='write review'
alias slides='write slides'
alias slog='subl $slog'
alias teach='pm teach'
alias tech='pm write tech'
alias task='pm task'
alias write='pm write'
alias words='write words'
alias workshop='write workshop'

# Workflow
alias cprc='cp ~/Hammer/config/zshrc ~/.zshrc && . ~/.zshrc'
alias todo='pm todo'
alias build='d && pm build'
alias epub='d $w && open textbook.epub'
alias dropbox='cp $w/textbook.epub ~/Dropbox/Stacie-Mark/PythonWebApps'
alias m='e Documents/mastodon'
alias a='d ~/Archive'

# Linux command context
alias g='grep --color=auto'
alias l='ls -al'
alias lc='wc -l'
alias u='d ..'
alias host=hostname
alias h='history 100'
alias p=python

# Git aliases
alias s='git status'
alias gh='d $g'
alias gl='git log --name-only'
alias gd='git diff'
alias ga='git add -A . && git commit -m'
alias gco='git checkout'
alias vc='cd $p && pm vc'
alias pull='pm vc pull'
alias push='pm vc push'
alias deploy='pm vc deploy'

# Django aliases
alias pm='python manage.py'
alias r='pm runserver 8000'
alias t='reset && pm tst run'
alias serve='pm runserver 8000'
alias dt='pm test'
alias migrate='pm makemigrations && pm migrate'
alias mm='pm makemigrations'
alias web='open http://markseaman.info'
alias w='open http://markseaman.info'

# Servers
alias imac='ssh seaman@marks-imac.local'
alias macbook='ssh markseaman@marks-macbook.local'
alias ntsh='. $n/zshrc'
alias unpack='pm pack open'
alias pack='pm pack close'
alias imager='pm imager'

# Test aliases
alias tst='pm tst run'
alias tlike='pm tst like && tst'
alias tres='pm tst results | less'
alias treset='pm tst reset'
alias qt='pm tst quick'



# Linux functions
function d {
    directory=$1
    [ -z "$1" ] && directory="$p"
    [ -z "$1" ] || echo $directory && cd $directory && l
}

# Big commit on current directory
function c {
    git pull           &&
    git add -A .       &&
    git commit -m "$*" &&
    git push
    git status
}

# Small commit on current directory
function gc {
    git add -A .       &&
    git commit -m "$*"
}

# Copy a file tree
function cptree {
    rsync -auv "$1/" "$2"
}

# Create a post on mastodon
function post {
    msg=`cat Documents/mastodon/$1`
    echo toot post \"$msg\"
}

# List the path in readable form
function path {
    echo $PATH | perl -pe s/:/\\n/g
}

# Show the Python setup
function py {
    echo "Python environment"
    echo PYTHON_PATH = `which python`
    echo PYENV = `pyenv which python`
    echo "Python Packages"
    pip freeze
}


# DocEnv
export DJANGO_SUPERUSER_USERNAME='seaman'
export DJANGO_SUPERUSER_PASSWORD='seaman'
export DJANGO_SUPERUSER_EMAIL='seaman'


# # Node environment
# export NVM_DIR="$HOME/.nvm"
# [[ -s "$NVM_DIR/nvm.sh" ]] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [[ -s "$NVM_DIR/bash_completion" ]] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Python
. ~/Hammer/.venv/bin/activate
export PS1="%3~ : "


# Start directory
cd ~/Hammer
ls
# figlet Hammer Time


